---
- name: Configuration de base des serveurs
  hosts: all
  become: yes
  roles:
    - role: common
      tags: [common] 

- name : Configuration des bases de données 
  hosts: staging_db:prod_db
  become: yes
  roles:
    - role: mysql
      tags: [db]  
